gate: cnot
qubits: 2
particles: 6
groups: 2,4
branch_config:
    - double
    - adjacent
    - clockwise
braid_sequence:
    - 3,4,0
    - 3,5,0
    - 1,2,0
    - 4,5,0
    - 3,6,0
    - 4,6,0
    - 5,6,0
